name: API Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra
    
    - name: Start server
      run: npm start &
    
    - name: Wait for server
      run: npx wait-on http://localhost:5000/api/health
    
    - name: Run API tests
      run: npm run test:api:html
    
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: api-test-report
        path: reports/